services:
  postgres:
    image: postgres:11.5
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./data-test/pgdata:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3.9.5
    restart: always
    hostname: rabbitmq
    container_name: rabbitmq
    expose:
      - "5672"
    logging:
      options:
        max-size: 10m
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"


networks:
  default: